[package]
name = "stat-filter"
version = "0.0.1"
authors = ["Takashi Yoneuchi <t.yoneuchi@flatt.tech>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
log = "0.4.11"

[dependencies.proxy-wasm]
version = "0.1.3"
features = ["wee-alloc"]